name: Deploy Middleman to GH Pages
 
on:
  push:
    tags: '*'
 
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Dependencies
        run: docker-compose build

      - name: Build site
        run: docker-compose run --rm web bundle exec middleman build --verbose

      - name: Deploy to AWS
        run: docker-compose run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} web bundle exec middleman s3_sync
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
